#!/usr/bin/env python3
"""
Create a Spotify playlist from a yttoplaylist JSON output.

First run: opens your browser to authorize. After you authorize, Spotify
redirects to a URL that won't load (that's OK). Copy that full URL and
paste it when prompted, OR pass it as the third argument.

Usage:
  python create_playlist.py tracklist.json "Playlist Name"
  python create_playlist.py tracklist.json "Playlist Name" "https://127.0.0.1:8888/callback?code=..."
"""
import json
import os
import sys
import webbrowser

import spotipy
from spotipy.oauth2 import SpotifyOAuth


CLIENT_ID = os.environ.get("SPOTIPY_CLIENT_ID", "cbad173853dc45ea955f58b7de7ddf04")
CLIENT_SECRET = os.environ.get("SPOTIPY_CLIENT_SECRET", "3de09866e3ce4cbeb133eef0c6bdbfc4")
REDIRECT_URI = os.environ.get("SPOTIPY_REDIRECT_URI", "https://127.0.0.1:8888/callback")
CACHE_PATH = os.path.expanduser("~/.cache/yttoplaylist_spotify_token")
SCOPE = "playlist-modify-public playlist-modify-private"


def get_spotify_client(redirect_url: str = None) -> spotipy.Spotify:
    """Get an authenticated Spotify client, handling the OAuth flow."""
    auth_manager = SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope=SCOPE,
        cache_path=CACHE_PATH,
        open_browser=False,  # We handle the browser ourselves
    )

    # Check if we have a cached token
    token_info = auth_manager.cache_handler.get_cached_token()
    if token_info and not auth_manager.is_token_expired(token_info):
        return spotipy.Spotify(auth_manager=auth_manager)

    if redirect_url:
        # User provided the redirect URL directly
        code = auth_manager.parse_response_code(redirect_url)
        auth_manager.get_access_token(code, as_dict=False)
        return spotipy.Spotify(auth_manager=auth_manager)

    # No cached token, need to authorize
    auth_url = auth_manager.get_authorize_url()
    print("\n=== SPOTIFY AUTHORIZATION ===")
    print("Opening your browser to authorize...")
    print(f"\nIf it doesn't open, go to:\n{auth_url}\n")
    webbrowser.open(auth_url)

    print("After authorizing, Spotify will redirect to a page that won't load.")
    print("That's OK! Copy the FULL URL from your browser's address bar and")
    print("re-run this command with the URL as the third argument:")
    print(f"\n  python create_playlist.py <json_file> <playlist_name> \"<paste_url_here>\"\n")
    sys.exit(0)


def main():
    if len(sys.argv) < 3:
        print("Usage: python create_playlist.py <tracklist.json> <playlist_name> [redirect_url]")
        print("\nFirst run will open browser for Spotify authorization.")
        sys.exit(1)

    json_path = sys.argv[1]
    playlist_name = sys.argv[2]
    redirect_url = sys.argv[3] if len(sys.argv) > 3 else None

    with open(json_path) as f:
        tracks = json.load(f)

    print(f"Loaded {len(tracks)} tracks from {json_path}")

    sp = get_spotify_client(redirect_url)

    user = sp.current_user()
    print(f"Logged in as: {user.get('display_name', user['id'])}")

    # Search for each track
    uris = []
    not_found = []
    for i, track in enumerate(tracks, 1):
        q = f"{track['artist']} {track['title']}"
        results = sp.search(q=q, type="track", limit=1)
        items = results.get("tracks", {}).get("items", [])
        if items:
            uris.append(items[0]["uri"])
            name = items[0]["name"]
            artists = ", ".join(a["name"] for a in items[0]["artists"])
            print(f"  {i:2d}. FOUND: {artists} - {name}")
        else:
            not_found.append(f"{track['artist']} - {track['title']}")
            print(f"  {i:2d}. NOT FOUND: {track['artist']} - {track['title']}")

    print(f"\nFound {len(uris)}/{len(tracks)} on Spotify")

    if not uris:
        print("No tracks to add!")
        sys.exit(1)

    # Create playlist — use the /me/ endpoint (required for dev mode apps)
    import requests
    token = sp.auth_manager.get_access_token(as_dict=False)
    resp = requests.post(
        "https://api.spotify.com/v1/me/playlists",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={
            "name": playlist_name,
            "public": True,
            "description": f"Auto-generated by yttoplaylist — {len(uris)} tracks detected via Shazam",
        },
    )
    if resp.status_code != 201:
        print(f"ERROR creating playlist: {resp.status_code} {resp.text}")
        sys.exit(1)

    playlist = resp.json()
    playlist_id = playlist["id"]

    # Add tracks
    for i in range(0, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i:i + 100])

    url = playlist["external_urls"]["spotify"]
    print(f"\n=== PLAYLIST CREATED ===")
    print(f"  Name: {playlist_name}")
    print(f"  Tracks: {len(uris)}")
    print(f"  URL: {url}")

    if not_found:
        print(f"\nNot found on Spotify ({len(not_found)}):")
        for t in not_found:
            print(f"  - {t}")


if __name__ == "__main__":
    main()
